-- ============================================================
--  La chica de las Cookies - Schema de productos (Supabase)
--  Ejecutá este bloque en: Supabase > SQL Editor > New query
-- ============================================================

create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  price       numeric(10,2) not null default 0,
  category    text not null check (category in ('cookies', 'frozen')),
  image       text,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

-- Permitir que la app (anon key) pueda LEER los productos.
alter table public.products enable row level security;

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read"
  on public.products
  for select
  using (true);

-- ============================================================
--  Seed - datos iniciales (3 cookies + 3 congeladas)
-- ============================================================
insert into public.products (name, description, price, category, image, sort_order) values
  ('Classic Choco Chip', 'La clásica con trozos generosos de chocolate semi-amargo.', 3500, 'cookies', '/cookies-classic.svg', 1),
  ('Double Chocolate', 'Masa de cacao intenso con chips de chocolate blanco y negro.', 4000, 'cookies', '/cookies-double.svg', 2),
  ('Oatmeal Raisin', 'Avena tostada con pasas maceradas y un toque de canela.', 3800, 'cookies', '/cookies-oatmeal.svg', 3),
  ('Frozen Nutella', 'Rellena de Nutella, horneada al momento y servida tibia.', 4500, 'frozen', '/cookies-frozen-nutella.svg', 4),
  ('Frozen Red Velvet', 'Red velvet con queso crema reservada para hornear en casa.', 4200, 'frozen', '/cookies-frozen-redvelvet.svg', 5),
  ('Frozen Matcha', 'Masa de matcha con chispas de chocolate blanco, lista para hornear.', 4600, 'frozen', '/cookies-frozen-matcha.svg', 6)
on conflict (id) do nothing;
